volumes:
  db-data:
  
services:
  db_migration:
    build:
      context: ../../
      dockerfile: ./deploy/compose/api/Dockerfile
  
    restart: on-failure
    volumes:
      - ../../alembic.ini:/app/alembic.ini:ro
      - ../../app/:/app/app/

    environment:
      DATABASE_URL: ${DATABASE_URL}
      TRON_RPC_URL: ${TRON_RPC_URL}
      TRON_RPC_API_KEY: ${TRON_RPC_API_KEY}

    depends_on:
      app-db:
        condition: service_healthy

    command: ["alembic", "upgrade", "head"]
    
  app-db:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

    ports:
      - 5431:5432